puts("Enter a color:\n")
color = gets().chomp()
puts("Enter a noun:\n")
noun = gets().chomp()
puts("Enter a name:\n")
name = gets().chomp()
puts ("rose are "+color)
puts (noun+" are blue")
puts ("i love "+name)
